INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Secretariat', N'Aintree', N'2017-05-12', CAST(11.5800 AS Money), 1)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Citation', N'Kilbeggan', N'2016-12-20', CAST(20.0000 AS Money), 0)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Citation', N'Punchestown', N'2016-12-22', CAST(122.5200 AS Money), 1)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Affirmed', N'Sandown', N'2016-11-17', CAST(20.0000 AS Money), 0)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Agile', N'Ascot', N'2018-05-01', CAST(11.5700 AS Money), 1)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Babcock', N'Aintree', N'2018-05-01', CAST(12.0000 AS Money), 0)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Seabiscuit', N'Ayr', N'2016-11-03', CAST(25.0000 AS Money), 0)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Man O War', N'Fairyhouse', N'2016-12-02', CAST(65.7500 AS Money), 1)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Secretariat', N'Ayr', N'2017-03-11', CAST(12.0500 AS Money), 1)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Agile', N'Doncaster', N'2017-12-02', CAST(10.0000 AS Money), 0)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Citation', N'Towcester', N'2016-03-12', CAST(50.0000 AS Money), 0)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Seabiscuit', N'Goodwood', N'2017-10-07', CAST(525.7400 AS Money), 1)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Affirmed', N'Kelso', N'2016-09-13', CAST(43.2100 AS Money), 1)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Man O War', N'Punchestown', N'2017-07-05', CAST(35.0000 AS Money), 0)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Seabiscuit', N'Ascot', N'2016-02-04', CAST(23.6500 AS Money), 1)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Citation', N'Kelso', N'2017-08-02', CAST(30.0000 AS Money), 0)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Secretariat', N'Towcester', N'2017-05-01', CAST(104.3300 AS Money), 1)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Agile', N'Ascot', N'2017-06-21', CAST(25.0000 AS Money), 0)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Man O War', N'Bangor', N'2016-12-22', CAST(30.0000 AS Money), 0)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Affirmed', N'Ayr', N'2017-05-22', CAST(11.5000 AS Money), 1)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Secretariat', N'Ascot', N'2017-06-23', CAST(30.0000 AS Money), 0)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Seabiscuit', N'Ascot', N'2017-06-23', CAST(374.2700 AS Money), 1)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Citation', N'Goodwood', N'2016-10-05', CAST(34.1200 AS Money), 1)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Agile', N'Dundalk', N'2016-11-09', CAST(20.0000 AS Money), 0)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Seabiscuit', N'Haydock', N'2016-11-12', CAST(87.0000 AS Money), 1)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Citation', N'Perth', N'2017-01-20', CAST(15.0000 AS Money), 0)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Affirmed', N'York', N'2017-11-11', CAST(101.2500 AS Money), 1)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Man O War', N'Punchestown', N'2016-12-22', CAST(11.5000 AS Money), 1)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Secretariat', N'Chester', N'2016-08-14', CAST(10.0000 AS Money), 0)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Seabiscuit', N'Kelso', N'2016-09-18', CAST(10.0000 AS Money), 0)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Agile', N'Kilbeggan', N'2017-03-03', CAST(20.0000 AS Money), 0)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Secretariat', N'Fairyhouse', N'2017-03-11', CAST(55.5000 AS Money), 1)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Citation', N'Punchestown', N'2016-11-15', CAST(10.0000 AS Money), 0)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Seabiscuit', N'Towcester', N'2016-05-05', CAST(16.5500 AS Money), 1)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Secretariat', N'Punchestown', N'2016-05-23', CAST(13.7100 AS Money), 1)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Agile', N'Cork', N'2016-11-30', CAST(20.0000 AS Money), 0)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Citation', N'Punchestown', N'2016-05-24', CAST(13.4500 AS Money), 1)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Affirmed', N'Bangor', N'2016-01-23', CAST(10.0000 AS Money), 0)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Seabiscuit', N'Sandown', N'2017-08-07', CAST(25.0000 AS Money), 0)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Citation', N'Kilbeggan', N'2017-12-18', CAST(10.0000 AS Money), 0)
INSERT INTO [dbo].[BetDetails] ([HorseName], [RaceCourse], [Date], [Amount], [Flag]) VALUES (N'Agile', N'Perth', N'2017-10-13', CAST(10.0000 AS Money), 0);


INSERT INTO [dbo].[Login] ([UserName], [Password]) VALUES (N'admin', N'admin')
INSERT INTO [dbo].[Login] ([UserName], [Password]) VALUES (N'', N'')
